# Generated by Django 6.0.7 on 2026-07-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaanalysisjob',
            name='analysis_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaanalysisjob',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaanalysisjob',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediaanalysisjob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediaanalysisjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('EXTRACTING_FRAMES', 'Extracting Frames'), ('ISOLATING_FACES', 'Isolating Faces'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=50),
        ),
    ]
